const IdentityRegistry = artifacts.require("IdentityRegistry");

/**
 * Test suite for IdentityRegistry Smart Contract.
 * Covers gasless registration via relayers and cryptographic login challenges.
 */
contract("IdentityRegistry", (accounts) => {
  let contractInstance;

  const RELAYER = accounts[0];
  const USER = accounts[1];
  const ATTACKER = accounts[2];

  const USERNAME = "KaisarGemini";
  const PUBKEY =
    "0x04bfcabf1c9e5e8a1d2c3e4f567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890";

  /**
   * Helper function to extract v, r, s variables from a standard cryptographic signature.
   * @param {string} signature - The hexadecimal signature string generated by web3.eth.sign
   * @returns {object} Object containing the extracted v, r, and s values
   */
  const splitSignature = (signature) => {
    const r = signature.slice(0, 66);
    const s = "0x" + signature.slice(66, 130);
    const v = web3.utils.toDecimal("0x" + signature.slice(130, 132)) + 27;
    return { v, r, s };
  };

  before(async () => {
    contractInstance = await IdentityRegistry.deployed();
    console.log("Contract Address:", contractInstance.address);
    console.log("User Address:", USER);
    console.log("Relayer Address:", RELAYER);
  });

  it("Should successfully execute gasless registration via Relayer", async () => {
    const messageHash = web3.utils.soliditySha3(
      { t: "address", v: USER },
      { t: "string", v: USERNAME },
      { t: "string", v: PUBKEY },
    );

    const signature = await web3.eth.sign(messageHash, USER);
    const { v, r, s } = splitSignature(signature);

    await contractInstance.registerUser(USER, USERNAME, PUBKEY, v, r, s, {
      from: RELAYER,
    });

    const userInfo = await contractInstance.getUser(USER);

    assert.equal(userInfo[0], USERNAME, "Username mismatch after registration");
    console.log("Gasless registration successful for:", userInfo[0]);
  });

  it("Should successfully validate login using nonce signature", async () => {
    const NONCE = "AUTH-CHALLENGE-12345";
    const nonceHash = web3.utils.soliditySha3(NONCE);

    const signature = await web3.eth.sign(nonceHash, USER);
    const { v, r, s } = splitSignature(signature);

    const isValid = await contractInstance.verifyLoginSignature(
      USER,
      NONCE,
      v,
      r,
      s,
    );

    assert.equal(isValid, true, "Valid signature was rejected");
    console.log("Login validation successful.");
  });

  it("Should reject login attempt with mismatched signature", async () => {
    const NONCE = "AUTH-CHALLENGE-12345";
    const nonceHash = web3.utils.soliditySha3(NONCE);

    const attackerSignature = await web3.eth.sign(nonceHash, ATTACKER);
    const { v, r, s } = splitSignature(attackerSignature);

    const isValid = await contractInstance.verifyLoginSignature(
      USER,
      NONCE,
      v,
      r,
      s,
    );

    assert.equal(isValid, false, "Invalid signature bypassed security");
    console.log("Unauthorized access properly blocked.");
  });
});
